{% set name = "scripts" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scripts-{{ version }}.tar.gz
  sha256: dbdba267cf9e4b336d3cac2eb862244abb2166c01cc95db704bd26e2ce8a75d3

build:
  entry_points:
    - cdblank = scripts.cdblank:main
    - cdriso = scripts.cdriso:main
    - cdwrite = scripts.cdwrite:main
    - my-backup = scripts.my_backup:main
    - pg-backup = scripts.pg_backup:main
    - pkg = scripts.pkg:main
    - unpkg = scripts.unpkg:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - stua
    - pip
  run:
    - python >=3.8
    - stua

test:
  imports:
    - scripts
  commands:
    - pip check
    - cdblank --help
    - cdriso --help
    - cdwrite --help
    - my-backup --help
    - pg-backup --help
    - pkg --help
    - unpkg --help
  requires:
    - pip

about:
  home: https://github.com/rsalmaso/scripts
  summary: Various linux scripts
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - mediocretech
